/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.alex.common2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        assertEquals("Hello world.", App.getGreeting());
    }
}
